-- MySQL Script generated by MySQL Workbench
-- Fri Jan 10 09:17:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetcoding
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetcoding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetcoding` DEFAULT CHARACTER SET latin1 ;
USE `projetcoding` ;

-- -----------------------------------------------------
-- Table `projetcoding`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetcoding`.`categorie` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetcoding`.`sous_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetcoding`.`sous_categorie` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `categorie_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `categorie_id`),
  INDEX `fk_sous_categorie_categorie_idx` (`categorie_id` ASC) ,
  CONSTRAINT `fk_sous_categorie_categorie`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `projetcoding`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetcoding`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetcoding`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetcoding`.`sujets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetcoding`.`sujets` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `sous_categorie_id` INT(10) UNSIGNED NOT NULL,
  `sous_categorie_categorie_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `sous_categorie_id`, `sous_categorie_categorie_id`),
  INDEX `fk_sujets_user1_idx` (`user_id` ASC) ,
  INDEX `fk_sujets_sous_categorie1_idx` (`sous_categorie_id` ASC, `sous_categorie_categorie_id` ASC) ,
  CONSTRAINT `fk_sujets_sous_categorie1`
    FOREIGN KEY (`sous_categorie_id` , `sous_categorie_categorie_id`)
    REFERENCES `projetcoding`.`sous_categorie` (`id` , `categorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sujets_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetcoding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projetcoding`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetcoding`.`commentaire` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `texte` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `sujets_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `sujets_id`, `user_id`),
  INDEX `fk_commentaire_sujets_idx` (`sujets_id` ASC) ,
  INDEX `fk_commentaire_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_commentaire_sujets`
    FOREIGN KEY (`sujets_id`)
    REFERENCES `projetcoding`.`sujets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetcoding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
